# Generated by Django 6.0.4 on 2026-04-09 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='specialite',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='dimensions',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dimensions (cm)'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='matiere',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Matière(s)'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='periode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Période / Année'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='region',
            field=models.CharField(blank=True, choices=[('cotonou', 'Cotonou'), ('porto-novo', 'Porto-Novo'), ('ouidah', 'Ouidah'), ('abomey', 'Abomey'), ('parakou', 'Parakou'), ('natitingou', 'Natitingou'), ('autre', 'Autre')], max_length=50, null=True, verbose_name="Région d'origine"),
        ),
        migrations.AddField(
            model_name='artwork',
            name='signification',
            field=models.TextField(blank=True, null=True, verbose_name='Signification culturelle'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='technique',
            field=models.CharField(blank=True, choices=[('bronze', 'Fonte au bronze'), ('bois', 'Sculpture sur bois'), ('textile', 'Tissage / Textile'), ('ceramique', 'Céramique / Poterie'), ('cauris', 'Art des Cauris'), ('peinture', 'Peinture sur tissu'), ('vannerie', 'Vannerie'), ('autre', 'Autre')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='ville',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='storytelling_texte',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='museum',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='museum',
            name='ville',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='ArtworkPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='artwork_photos/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.artwork')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
