services:
  - type: web
    name: mon-histoire-backend
    runtime: python
    rootDir: .
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application --bind 0.0.0.0:$PORT --workers 2"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.0"
